version: '2'
services:
  docker-mysql:
    image: mysql
    container_name: docker-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "cats"
      MYSQL_USER: "cat"
      MYSQL_PASSWORD: "meow"
      MYSQL_ROOT_PASSWORD: "mysql"