docker-mysql:
  image: mysql
  container_name: docker-mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "cats"
    MYSQL_USER: "cat"
    MYSQL_PASSWORD: "meow"
    MYSQL_ROOT_PASSWORD: "mysql"