apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alpine
  labels:
    application: alpine
  template:
    metadata:
      labels:
        app: alpine
spec:
  containers:
  - image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP
      - name: ssh
        containerPort: 22
        protocol: TCP
