apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cats
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cats
    spec:
      containers:
      - image: hinunbi/cats
        name: cats
        env:
        - name: ACTIVEMQ_BROKER_URL
          value: "ssl://broker-amq-tcp-ssl-container-workshop.apps.13.124.168.242.nip.io:443"
        ports:
        - containerPort: 8080
          name: cats
        command: ["java"]
        args:    ["-Djavax.net.ssl.trustStore=ssl/client.ts", "-Duser.timezone=GMT+09:00","-jar","cats-1.0.jar"]